#Server Configuration
server:
  port: 8888

#Spring Configuration
spring:
  application:
    name:
      gambit-config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitlab.com/riggtravis/config-debug.git
#          username:
#          password:
          clone-on-start: true

#Kafka Configuration
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: gambit
    bootstrap-servers:
    - ${KAFKA_URL}
