#Server Configuration
server:
  port: 8888

#Spring Configuration
spring:
  application:
    name:
      gambit-config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URL}
          username: ${CONFIG_REPO_USERNAME}
          password: ${CONFIG_REPO_PASSWORD}
          clone-on-start: true

#Kafka Configuration
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: gambit
    bootstrap-servers:
    - ${KAFKA_URL}
