server:
  port: 8888

spring:
  application:
    name:
      gambit-config-server
  cloud:
    config:
      server:
        git:
          uri: ${CONFIG_REPO_URL}
          username: ${CONFIG_REPO_USERNAME}
          password: ${CONFIG_REPO_PASSWORD}
  kafka:
    consumer:
      auto-offset-reset: earliest
      group-id: gambit
    bootstrap-servers:
    - ${KAFKA_URL}
